int32 index
---
bool success
float64[6] pick_observation_pose
float64[6] place_observation_pose
float64 row
float64 col
string category
float64 detected_angle_deg
float64 rotation_delta_deg
string message
