int32 index
---
bool success
float64[6] pick_observation_pose
float64[6] place_observation_pose
float64 row
float64 col
string category
float64 detected_angle_deg
float64 rotation_delta_deg
float64 pick_surface_z_mm
bool pick_surface_z_valid
float64[2] pick_high_detected_pixel_xy
float64[2] pick_high_depth_sample_pixel_xy
float64[2] pick_high_image_center_xy
float64[3] pick_high_world_position
bool pick_high_world_position_valid
string pick_rough_localization_source
int32 pick_depth_valid_frame_count
float64 pick_depth_median_mm
float64 pick_depth_mad_mm
float64 pick_calibration_target_tcp_z_mm
float64[2] place_high_detected_pixel_xy
float64[2] place_high_depth_sample_pixel_xy
float64[2] place_high_image_center_xy
float64[3] place_high_world_position
bool place_high_world_position_valid
string place_rough_localization_source
int32 place_depth_valid_frame_count
float64 place_depth_median_mm
float64 place_depth_mad_mm
float64 place_calibration_target_tcp_z_mm
string message
