<?xml version="1.0"?>
<package format="2">
  <name>image_process</name>
  <version>0.1.0</version>
  <description>方块与托盘粗定位、任务规划和低位视觉伺服检测</description>
  <maintainer email="zhl@todo.todo">zhl</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <depend>camera</depend>
  <depend>cv_bridge</depend>
  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>message_runtime</exec_depend>
</package>
