# RGB相机
rgb_camera:
  # 自动曝光
  auto_exposure: True
  # 手动设置曝光值
  #   注意事项: 当auto_exposure=False时有效
  # exposure: 70
  # 增益
  #   注意事项: 当auto_exposure=False时有效
  # gain: 16
  # 相机亮度
  #   注意事项: 当auto_exposure=True时有效
  brightness: 35
  # 自动白平衡
  auto_white_balance: True
  # 手动设置白平衡
  #   注意事项: 当auto_white_balance=False时有效
  white_balance: 5000
  # 锐度默认
  sharpness: 50
  # 伽马默认
  gamma: 300
  # 饱和度
  saturation: 70
  # 对比度
  contrast: 50
  # 电力线频率
  power_line_frequency: 0
# 深度相机
depth_camera:
  # 自动曝光
  auto_exposure: True
  # 手动设置曝光值
  #   注意事项: 当auto_exposure=False时有效
  exposure: 3000
  # 增益
  #   注意事项: 当auto_exposure=False时有效
  gain: 1000
  # 深度工作模式
  # 序号[0] 名称: Default
  # 序号[1] 名称: Hand
  # 序号[2] 名称: High Accuracy
  # 序号[3] 名称: High Density
  # 序号[4] 名称: Medium Density
  # 序号[5] 名称: Factory Calib
  depth_work_mode: 2
