<?xml version="1.0"?>
<package format="2">
  <name>competition</name>
  <version>0.1.0</version>
  <description>单臂俄罗斯方块任务总控与视觉伺服执行</description>
  <maintainer email="zhl@todo.todo">zhl</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>control</depend>
  <depend>image_process</depend>
  <depend>rospy</depend>
</package>
