detect_model: /home/zhl/SingleArmTetris/SingleArmTetris/src/competition/model/best5.14.pt
seg_model: /home/zhl/SingleArmTetris/SingleArmTetris/src/competition/model/best_seg.engine
template_sizes:
  active_profile: high
  profiles:
    high:
      block_px: 37
      connector_px: 5
    low:
      block_px: 81
      connector_px: 11

color_segmentation:
  seed_search_half_size: 40
  seed_patch_size: 7
  seed_stride: 8
  local_dist_thresh: 45
  categories:
    line:
      rgb: [63, 44, 47]
    square:
      rgb: [129, 65, 53]
    T:
      rgb: [55, 67, 63]
    L_yellow:
      rgb: [115, 117, 40]
    L_blue:
      rgb: [49, 62, 83]
    z_green:
      rgb: [45, 84, 64]
    z_blue:
      rgb: [48, 77, 107]

#真实长度测量
# line:   17.8  78.2
# buleL:  58.3  37.8
# yellowL:58.1  38.0
# T:      58.0  38.1  
# greenZ: 58.0  38.0
# buleZ:  58.2  38.1
# square: 38.1  38.1 
