<?xml version="1.0"?>
<package format="2">
  <name>camera</name>
  <version>0.1.0</version>
  <description>Gemini335 彩色图像发布与批量稳定世界坐标查询服务</description>
  <maintainer email="zhl@todo.todo">zhl</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <depend>cv_bridge</depend>
  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>message_runtime</exec_depend>
</package>
